/**
 * Auto-generated route definitions
 * 
 * This file is generated by scripts/gen_routes.ts
 * Do not edit manually. Run "pnpm gen:routes" to regenerate.
 * 
 * Generated at: 2026-02-25T11:51:23.990Z
 */

export type RouteKey =
  "/" |
  "/blog" |
  "/blog/[slug]" |
  "/dp" |
  "/services" |
  "/theme-demo";

export type RouteParams = {
  "/": Record<string, never>;
  "/blog": Record<string, never>;
  "/blog/[slug]": {
  slug: string;
};
  "/dp": Record<string, never>;
  "/services": Record<string, never>;
  "/theme-demo": Record<string, never>;
};

export const root = () => `/`;

export const blog = () => `/blog`;

export const blog_slug = (p: {
  slug: string;
}) => `/blog/${p.slug}`;

export const dp = () => `/dp`;

export const services = () => `/services`;

export const theme_demo = () => `/theme-demo`;

export const routes = {
  root,
  blog,
  blog_slug,
  dp,
  services,
  theme_demo,
} as const;

export function buildPath<K extends RouteKey>(
  route: K,
  params: RouteParams[K]
): string {
  switch (route) {
    case "/":
      return root();
    case "/blog":
      return blog();
    case "/blog/[slug]":
      return blog_slug(params as RouteParams["/blog/[slug]"]);
    case "/dp":
      return dp();
    case "/services":
      return services();
    case "/theme-demo":
      return theme_demo();
    default:
      const _exhaustive: never = route;
      return _exhaustive;
  }
}
