/**
 * This is an autogenerated file that contains a list of all of the blog posts in the blog directory.
 * It also has some derived types objects used in sub indexes.
 * Generated at: 2026-02-25T11:48:46.954Z
 */

import {PostMetadata, PostSpec} from './_types';

import bom_scraping_on_gcpContent from './(2025)/bom-scraping-on-gcp/page.mdx';
import shouldContent from './(2026)/should/page.mdx';
import automation_of_personal_share_reportingContent from './(2025)/automation-of-personal-share-reporting/page.mdx';
import conflation_in_religious_discussionContent from './(2025)/conflation-in-religious-discussion/page.mdx';
import logseq_pkmContent from './(2025)/logseq-pkm/page.mdx';
import learning_ai_waste_2025Content from './(2025)/learning-ai-waste-2025/page.mdx';
import imperfectionContent from './(2025)/imperfection/page.mdx';

// A list of all of the posts in order of first, if they're featured, then by date.
export const AllPosts: PostSpec[] = [
  {
    slug: 'bom-scraping-on-gcp',
    title: 'BOM Scraping On GCP',
    date: new Date('2025-04-29T00:00:00.000Z'),
    tags: ['cloud', 'gcp', 'python', 'automation', 'weather', 'bom', 'radar', 'scraping'],
    excerpt: 'Building a lightweight cloud-native radar data pipeline to extract spatial rainfall patterns from Bureau of Meteorology radar images using Google Cloud Platform.',
    image: '/blog/bom-scraping-on-gcp/images_bris_128_202504291340.webp',
    imageAlt: 'BOM radar rainfall image showing spatial rainfall patterns around Brisbane (128km coverage)',
    readingTime: 6,
    isFeatured: true,
    Content: bom_scraping_on_gcpContent
  },
  {
    slug: 'should',
    title: 'You should read this.',
    date: new Date('2026-02-08T00:00:00.000Z'),
    tags: ['philosophy', 'language', 'culture'],
    excerpt: 'Making a should statement always has an implicit value-statement or perspective attached. A note on top-down vs bottom-up framing.',
    readingTime: 3,
    isFeatured: false,
    Content: shouldContent
  },
  {
    slug: 'automation-of-personal-share-reporting',
    title: 'Automation of Personal Share Reporting',
    date: new Date('2025-09-11T00:00:00.000Z'),
    tags: ['automation', 'ai', 'cloud', 'gcp', 'investment', 'technology', 'n8n', 'pdf-processing'],
    excerpt: 'Automating trade logging from CMC Markets using n8n, LLMs, and Google Sheets to transform PDF trade confirmations into structured data.',
    image: '/blog/automation-of-personal-share-reporting/architecture.webp',
    imageAlt: 'Architecture diagram of automated trade reporting system',
    readingTime: 6,
    isFeatured: false,
    Content: automation_of_personal_share_reportingContent
  },
  {
    slug: 'conflation-in-religious-discussion',
    title: 'Common conflation of religious concepts',
    date: new Date('2025-09-08T00:00:00.000Z'),
    tags: ['philosophy', 'religion', 'spirituality', 'discussion'],
    excerpt: 'Teasing apart distinct concepts in religious and spiritual discussions to enable clearer dialogue and reduce unnecessary confusion.',
    readingTime: 5,
    isFeatured: false,
    Content: conflation_in_religious_discussionContent
  },
  {
    slug: 'logseq-pkm',
    title: 'Building a Personal Knowledge Management Stack with GCP and Logseq',
    date: new Date('2025-09-08T00:00:00.000Z'),
    tags: ['cloud', 'gcp', 'logseq', 'knowledge-management', 'automation', 'sync'],
    excerpt: 'Building a synchronized personal knowledge management system using Logseq, Google Cloud Platform, and cross-device synchronization.',
    image: '/blog/logseq-pkm/logseqarch.webp',
    imageAlt: 'Logseq PKM architecture diagram showing GCP integration',
    readingTime: 4,
    isFeatured: false,
    Content: logseq_pkmContent
  },
  {
    slug: 'learning-ai-waste-2025',
    title: 'Learning AI & Waste',
    date: new Date('2025-04-18T20:42:00.000Z'),
    tags: ['philosophy', 'AI'],
    excerpt: 'A blog post about learning AI and waste',
    readingTime: 3,
    isFeatured: false,
    Content: learning_ai_waste_2025Content
  },
  {
    slug: 'imperfection',
    title: 'Imperfection',
    date: new Date('2025-04-17T06:23:00.000Z'),
    tags: ['philosophy', 'personal-improvement'],
    excerpt: 'My First Post',
    readingTime: 0.5,
    isFeatured: false,
    Content: imperfectionContent
  }
]

// A list of each of the tags and the posts that have that tag.
export const TagsIndex: Record<string, PostSpec[]> = {
  'automation': [
      {
        slug: 'bom-scraping-on-gcp',
        title: 'BOM Scraping On GCP',
        date: new Date('2025-04-29T00:00:00.000Z'),
        tags: ['cloud', 'gcp', 'python', 'automation', 'weather', 'bom', 'radar', 'scraping'],
        excerpt: 'Building a lightweight cloud-native radar data pipeline to extract spatial rainfall patterns from Bureau of Meteorology radar images using Google Cloud Platform.',
        image: '/blog/bom-scraping-on-gcp/images_bris_128_202504291340.webp',
        imageAlt: 'BOM radar rainfall image showing spatial rainfall patterns around Brisbane (128km coverage)',
        readingTime: 6,
        isFeatured: true,
        Content: bom_scraping_on_gcpContent
      },
      {
        slug: 'automation-of-personal-share-reporting',
        title: 'Automation of Personal Share Reporting',
        date: new Date('2025-09-11T00:00:00.000Z'),
        tags: ['automation', 'ai', 'cloud', 'gcp', 'investment', 'technology', 'n8n', 'pdf-processing'],
        excerpt: 'Automating trade logging from CMC Markets using n8n, LLMs, and Google Sheets to transform PDF trade confirmations into structured data.',
        image: '/blog/automation-of-personal-share-reporting/architecture.webp',
        imageAlt: 'Architecture diagram of automated trade reporting system',
        readingTime: 6,
        isFeatured: false,
        Content: automation_of_personal_share_reportingContent
      },
      {
        slug: 'logseq-pkm',
        title: 'Building a Personal Knowledge Management Stack with GCP and Logseq',
        date: new Date('2025-09-08T00:00:00.000Z'),
        tags: ['cloud', 'gcp', 'logseq', 'knowledge-management', 'automation', 'sync'],
        excerpt: 'Building a synchronized personal knowledge management system using Logseq, Google Cloud Platform, and cross-device synchronization.',
        image: '/blog/logseq-pkm/logseqarch.webp',
        imageAlt: 'Logseq PKM architecture diagram showing GCP integration',
        readingTime: 4,
        isFeatured: false,
        Content: logseq_pkmContent
      }
  ],
  'ai': [
      {
        slug: 'automation-of-personal-share-reporting',
        title: 'Automation of Personal Share Reporting',
        date: new Date('2025-09-11T00:00:00.000Z'),
        tags: ['automation', 'ai', 'cloud', 'gcp', 'investment', 'technology', 'n8n', 'pdf-processing'],
        excerpt: 'Automating trade logging from CMC Markets using n8n, LLMs, and Google Sheets to transform PDF trade confirmations into structured data.',
        image: '/blog/automation-of-personal-share-reporting/architecture.webp',
        imageAlt: 'Architecture diagram of automated trade reporting system',
        readingTime: 6,
        isFeatured: false,
        Content: automation_of_personal_share_reportingContent
      }
  ],
  'cloud': [
      {
        slug: 'bom-scraping-on-gcp',
        title: 'BOM Scraping On GCP',
        date: new Date('2025-04-29T00:00:00.000Z'),
        tags: ['cloud', 'gcp', 'python', 'automation', 'weather', 'bom', 'radar', 'scraping'],
        excerpt: 'Building a lightweight cloud-native radar data pipeline to extract spatial rainfall patterns from Bureau of Meteorology radar images using Google Cloud Platform.',
        image: '/blog/bom-scraping-on-gcp/images_bris_128_202504291340.webp',
        imageAlt: 'BOM radar rainfall image showing spatial rainfall patterns around Brisbane (128km coverage)',
        readingTime: 6,
        isFeatured: true,
        Content: bom_scraping_on_gcpContent
      },
      {
        slug: 'automation-of-personal-share-reporting',
        title: 'Automation of Personal Share Reporting',
        date: new Date('2025-09-11T00:00:00.000Z'),
        tags: ['automation', 'ai', 'cloud', 'gcp', 'investment', 'technology', 'n8n', 'pdf-processing'],
        excerpt: 'Automating trade logging from CMC Markets using n8n, LLMs, and Google Sheets to transform PDF trade confirmations into structured data.',
        image: '/blog/automation-of-personal-share-reporting/architecture.webp',
        imageAlt: 'Architecture diagram of automated trade reporting system',
        readingTime: 6,
        isFeatured: false,
        Content: automation_of_personal_share_reportingContent
      },
      {
        slug: 'logseq-pkm',
        title: 'Building a Personal Knowledge Management Stack with GCP and Logseq',
        date: new Date('2025-09-08T00:00:00.000Z'),
        tags: ['cloud', 'gcp', 'logseq', 'knowledge-management', 'automation', 'sync'],
        excerpt: 'Building a synchronized personal knowledge management system using Logseq, Google Cloud Platform, and cross-device synchronization.',
        image: '/blog/logseq-pkm/logseqarch.webp',
        imageAlt: 'Logseq PKM architecture diagram showing GCP integration',
        readingTime: 4,
        isFeatured: false,
        Content: logseq_pkmContent
      }
  ],
  'gcp': [
      {
        slug: 'bom-scraping-on-gcp',
        title: 'BOM Scraping On GCP',
        date: new Date('2025-04-29T00:00:00.000Z'),
        tags: ['cloud', 'gcp', 'python', 'automation', 'weather', 'bom', 'radar', 'scraping'],
        excerpt: 'Building a lightweight cloud-native radar data pipeline to extract spatial rainfall patterns from Bureau of Meteorology radar images using Google Cloud Platform.',
        image: '/blog/bom-scraping-on-gcp/images_bris_128_202504291340.webp',
        imageAlt: 'BOM radar rainfall image showing spatial rainfall patterns around Brisbane (128km coverage)',
        readingTime: 6,
        isFeatured: true,
        Content: bom_scraping_on_gcpContent
      },
      {
        slug: 'automation-of-personal-share-reporting',
        title: 'Automation of Personal Share Reporting',
        date: new Date('2025-09-11T00:00:00.000Z'),
        tags: ['automation', 'ai', 'cloud', 'gcp', 'investment', 'technology', 'n8n', 'pdf-processing'],
        excerpt: 'Automating trade logging from CMC Markets using n8n, LLMs, and Google Sheets to transform PDF trade confirmations into structured data.',
        image: '/blog/automation-of-personal-share-reporting/architecture.webp',
        imageAlt: 'Architecture diagram of automated trade reporting system',
        readingTime: 6,
        isFeatured: false,
        Content: automation_of_personal_share_reportingContent
      },
      {
        slug: 'logseq-pkm',
        title: 'Building a Personal Knowledge Management Stack with GCP and Logseq',
        date: new Date('2025-09-08T00:00:00.000Z'),
        tags: ['cloud', 'gcp', 'logseq', 'knowledge-management', 'automation', 'sync'],
        excerpt: 'Building a synchronized personal knowledge management system using Logseq, Google Cloud Platform, and cross-device synchronization.',
        image: '/blog/logseq-pkm/logseqarch.webp',
        imageAlt: 'Logseq PKM architecture diagram showing GCP integration',
        readingTime: 4,
        isFeatured: false,
        Content: logseq_pkmContent
      }
  ],
  'investment': [
      {
        slug: 'automation-of-personal-share-reporting',
        title: 'Automation of Personal Share Reporting',
        date: new Date('2025-09-11T00:00:00.000Z'),
        tags: ['automation', 'ai', 'cloud', 'gcp', 'investment', 'technology', 'n8n', 'pdf-processing'],
        excerpt: 'Automating trade logging from CMC Markets using n8n, LLMs, and Google Sheets to transform PDF trade confirmations into structured data.',
        image: '/blog/automation-of-personal-share-reporting/architecture.webp',
        imageAlt: 'Architecture diagram of automated trade reporting system',
        readingTime: 6,
        isFeatured: false,
        Content: automation_of_personal_share_reportingContent
      }
  ],
  'technology': [
      {
        slug: 'automation-of-personal-share-reporting',
        title: 'Automation of Personal Share Reporting',
        date: new Date('2025-09-11T00:00:00.000Z'),
        tags: ['automation', 'ai', 'cloud', 'gcp', 'investment', 'technology', 'n8n', 'pdf-processing'],
        excerpt: 'Automating trade logging from CMC Markets using n8n, LLMs, and Google Sheets to transform PDF trade confirmations into structured data.',
        image: '/blog/automation-of-personal-share-reporting/architecture.webp',
        imageAlt: 'Architecture diagram of automated trade reporting system',
        readingTime: 6,
        isFeatured: false,
        Content: automation_of_personal_share_reportingContent
      }
  ],
  'n8n': [
      {
        slug: 'automation-of-personal-share-reporting',
        title: 'Automation of Personal Share Reporting',
        date: new Date('2025-09-11T00:00:00.000Z'),
        tags: ['automation', 'ai', 'cloud', 'gcp', 'investment', 'technology', 'n8n', 'pdf-processing'],
        excerpt: 'Automating trade logging from CMC Markets using n8n, LLMs, and Google Sheets to transform PDF trade confirmations into structured data.',
        image: '/blog/automation-of-personal-share-reporting/architecture.webp',
        imageAlt: 'Architecture diagram of automated trade reporting system',
        readingTime: 6,
        isFeatured: false,
        Content: automation_of_personal_share_reportingContent
      }
  ],
  'pdf-processing': [
      {
        slug: 'automation-of-personal-share-reporting',
        title: 'Automation of Personal Share Reporting',
        date: new Date('2025-09-11T00:00:00.000Z'),
        tags: ['automation', 'ai', 'cloud', 'gcp', 'investment', 'technology', 'n8n', 'pdf-processing'],
        excerpt: 'Automating trade logging from CMC Markets using n8n, LLMs, and Google Sheets to transform PDF trade confirmations into structured data.',
        image: '/blog/automation-of-personal-share-reporting/architecture.webp',
        imageAlt: 'Architecture diagram of automated trade reporting system',
        readingTime: 6,
        isFeatured: false,
        Content: automation_of_personal_share_reportingContent
      }
  ],
  'python': [
      {
        slug: 'bom-scraping-on-gcp',
        title: 'BOM Scraping On GCP',
        date: new Date('2025-04-29T00:00:00.000Z'),
        tags: ['cloud', 'gcp', 'python', 'automation', 'weather', 'bom', 'radar', 'scraping'],
        excerpt: 'Building a lightweight cloud-native radar data pipeline to extract spatial rainfall patterns from Bureau of Meteorology radar images using Google Cloud Platform.',
        image: '/blog/bom-scraping-on-gcp/images_bris_128_202504291340.webp',
        imageAlt: 'BOM radar rainfall image showing spatial rainfall patterns around Brisbane (128km coverage)',
        readingTime: 6,
        isFeatured: true,
        Content: bom_scraping_on_gcpContent
      }
  ],
  'weather': [
      {
        slug: 'bom-scraping-on-gcp',
        title: 'BOM Scraping On GCP',
        date: new Date('2025-04-29T00:00:00.000Z'),
        tags: ['cloud', 'gcp', 'python', 'automation', 'weather', 'bom', 'radar', 'scraping'],
        excerpt: 'Building a lightweight cloud-native radar data pipeline to extract spatial rainfall patterns from Bureau of Meteorology radar images using Google Cloud Platform.',
        image: '/blog/bom-scraping-on-gcp/images_bris_128_202504291340.webp',
        imageAlt: 'BOM radar rainfall image showing spatial rainfall patterns around Brisbane (128km coverage)',
        readingTime: 6,
        isFeatured: true,
        Content: bom_scraping_on_gcpContent
      }
  ],
  'bom': [
      {
        slug: 'bom-scraping-on-gcp',
        title: 'BOM Scraping On GCP',
        date: new Date('2025-04-29T00:00:00.000Z'),
        tags: ['cloud', 'gcp', 'python', 'automation', 'weather', 'bom', 'radar', 'scraping'],
        excerpt: 'Building a lightweight cloud-native radar data pipeline to extract spatial rainfall patterns from Bureau of Meteorology radar images using Google Cloud Platform.',
        image: '/blog/bom-scraping-on-gcp/images_bris_128_202504291340.webp',
        imageAlt: 'BOM radar rainfall image showing spatial rainfall patterns around Brisbane (128km coverage)',
        readingTime: 6,
        isFeatured: true,
        Content: bom_scraping_on_gcpContent
      }
  ],
  'radar': [
      {
        slug: 'bom-scraping-on-gcp',
        title: 'BOM Scraping On GCP',
        date: new Date('2025-04-29T00:00:00.000Z'),
        tags: ['cloud', 'gcp', 'python', 'automation', 'weather', 'bom', 'radar', 'scraping'],
        excerpt: 'Building a lightweight cloud-native radar data pipeline to extract spatial rainfall patterns from Bureau of Meteorology radar images using Google Cloud Platform.',
        image: '/blog/bom-scraping-on-gcp/images_bris_128_202504291340.webp',
        imageAlt: 'BOM radar rainfall image showing spatial rainfall patterns around Brisbane (128km coverage)',
        readingTime: 6,
        isFeatured: true,
        Content: bom_scraping_on_gcpContent
      }
  ],
  'scraping': [
      {
        slug: 'bom-scraping-on-gcp',
        title: 'BOM Scraping On GCP',
        date: new Date('2025-04-29T00:00:00.000Z'),
        tags: ['cloud', 'gcp', 'python', 'automation', 'weather', 'bom', 'radar', 'scraping'],
        excerpt: 'Building a lightweight cloud-native radar data pipeline to extract spatial rainfall patterns from Bureau of Meteorology radar images using Google Cloud Platform.',
        image: '/blog/bom-scraping-on-gcp/images_bris_128_202504291340.webp',
        imageAlt: 'BOM radar rainfall image showing spatial rainfall patterns around Brisbane (128km coverage)',
        readingTime: 6,
        isFeatured: true,
        Content: bom_scraping_on_gcpContent
      }
  ],
  'philosophy': [
      {
        slug: 'should',
        title: 'You should read this.',
        date: new Date('2026-02-08T00:00:00.000Z'),
        tags: ['philosophy', 'language', 'culture'],
        excerpt: 'Making a should statement always has an implicit value-statement or perspective attached. A note on top-down vs bottom-up framing.',
        readingTime: 3,
        isFeatured: false,
        Content: shouldContent
      },
      {
        slug: 'conflation-in-religious-discussion',
        title: 'Common conflation of religious concepts',
        date: new Date('2025-09-08T00:00:00.000Z'),
        tags: ['philosophy', 'religion', 'spirituality', 'discussion'],
        excerpt: 'Teasing apart distinct concepts in religious and spiritual discussions to enable clearer dialogue and reduce unnecessary confusion.',
        readingTime: 5,
        isFeatured: false,
        Content: conflation_in_religious_discussionContent
      },
      {
        slug: 'learning-ai-waste-2025',
        title: 'Learning AI & Waste',
        date: new Date('2025-04-18T20:42:00.000Z'),
        tags: ['philosophy', 'AI'],
        excerpt: 'A blog post about learning AI and waste',
        readingTime: 3,
        isFeatured: false,
        Content: learning_ai_waste_2025Content
      },
      {
        slug: 'imperfection',
        title: 'Imperfection',
        date: new Date('2025-04-17T06:23:00.000Z'),
        tags: ['philosophy', 'personal-improvement'],
        excerpt: 'My First Post',
        readingTime: 0.5,
        isFeatured: false,
        Content: imperfectionContent
      }
  ],
  'religion': [
      {
        slug: 'conflation-in-religious-discussion',
        title: 'Common conflation of religious concepts',
        date: new Date('2025-09-08T00:00:00.000Z'),
        tags: ['philosophy', 'religion', 'spirituality', 'discussion'],
        excerpt: 'Teasing apart distinct concepts in religious and spiritual discussions to enable clearer dialogue and reduce unnecessary confusion.',
        readingTime: 5,
        isFeatured: false,
        Content: conflation_in_religious_discussionContent
      }
  ],
  'spirituality': [
      {
        slug: 'conflation-in-religious-discussion',
        title: 'Common conflation of religious concepts',
        date: new Date('2025-09-08T00:00:00.000Z'),
        tags: ['philosophy', 'religion', 'spirituality', 'discussion'],
        excerpt: 'Teasing apart distinct concepts in religious and spiritual discussions to enable clearer dialogue and reduce unnecessary confusion.',
        readingTime: 5,
        isFeatured: false,
        Content: conflation_in_religious_discussionContent
      }
  ],
  'discussion': [
      {
        slug: 'conflation-in-religious-discussion',
        title: 'Common conflation of religious concepts',
        date: new Date('2025-09-08T00:00:00.000Z'),
        tags: ['philosophy', 'religion', 'spirituality', 'discussion'],
        excerpt: 'Teasing apart distinct concepts in religious and spiritual discussions to enable clearer dialogue and reduce unnecessary confusion.',
        readingTime: 5,
        isFeatured: false,
        Content: conflation_in_religious_discussionContent
      }
  ],
  'personal-improvement': [
      {
        slug: 'imperfection',
        title: 'Imperfection',
        date: new Date('2025-04-17T06:23:00.000Z'),
        tags: ['philosophy', 'personal-improvement'],
        excerpt: 'My First Post',
        readingTime: 0.5,
        isFeatured: false,
        Content: imperfectionContent
      }
  ],
  'AI': [
      {
        slug: 'learning-ai-waste-2025',
        title: 'Learning AI & Waste',
        date: new Date('2025-04-18T20:42:00.000Z'),
        tags: ['philosophy', 'AI'],
        excerpt: 'A blog post about learning AI and waste',
        readingTime: 3,
        isFeatured: false,
        Content: learning_ai_waste_2025Content
      }
  ],
  'logseq': [
      {
        slug: 'logseq-pkm',
        title: 'Building a Personal Knowledge Management Stack with GCP and Logseq',
        date: new Date('2025-09-08T00:00:00.000Z'),
        tags: ['cloud', 'gcp', 'logseq', 'knowledge-management', 'automation', 'sync'],
        excerpt: 'Building a synchronized personal knowledge management system using Logseq, Google Cloud Platform, and cross-device synchronization.',
        image: '/blog/logseq-pkm/logseqarch.webp',
        imageAlt: 'Logseq PKM architecture diagram showing GCP integration',
        readingTime: 4,
        isFeatured: false,
        Content: logseq_pkmContent
      }
  ],
  'knowledge-management': [
      {
        slug: 'logseq-pkm',
        title: 'Building a Personal Knowledge Management Stack with GCP and Logseq',
        date: new Date('2025-09-08T00:00:00.000Z'),
        tags: ['cloud', 'gcp', 'logseq', 'knowledge-management', 'automation', 'sync'],
        excerpt: 'Building a synchronized personal knowledge management system using Logseq, Google Cloud Platform, and cross-device synchronization.',
        image: '/blog/logseq-pkm/logseqarch.webp',
        imageAlt: 'Logseq PKM architecture diagram showing GCP integration',
        readingTime: 4,
        isFeatured: false,
        Content: logseq_pkmContent
      }
  ],
  'sync': [
      {
        slug: 'logseq-pkm',
        title: 'Building a Personal Knowledge Management Stack with GCP and Logseq',
        date: new Date('2025-09-08T00:00:00.000Z'),
        tags: ['cloud', 'gcp', 'logseq', 'knowledge-management', 'automation', 'sync'],
        excerpt: 'Building a synchronized personal knowledge management system using Logseq, Google Cloud Platform, and cross-device synchronization.',
        image: '/blog/logseq-pkm/logseqarch.webp',
        imageAlt: 'Logseq PKM architecture diagram showing GCP integration',
        readingTime: 4,
        isFeatured: false,
        Content: logseq_pkmContent
      }
  ],
  'language': [
      {
        slug: 'should',
        title: 'You should read this.',
        date: new Date('2026-02-08T00:00:00.000Z'),
        tags: ['philosophy', 'language', 'culture'],
        excerpt: 'Making a should statement always has an implicit value-statement or perspective attached. A note on top-down vs bottom-up framing.',
        readingTime: 3,
        isFeatured: false,
        Content: shouldContent
      }
  ],
  'culture': [
      {
        slug: 'should',
        title: 'You should read this.',
        date: new Date('2026-02-08T00:00:00.000Z'),
        tags: ['philosophy', 'language', 'culture'],
        excerpt: 'Making a should statement always has an implicit value-statement or perspective attached. A note on top-down vs bottom-up framing.',
        readingTime: 3,
        isFeatured: false,
        Content: shouldContent
      }
  ]
}
